name: FRONTEND Update Main

on:
  push:
    branches:
      - main
      - master

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: tobbe-joh/noq_app_fork
          ref: main

      - name: Create Pull Request
        uses: ./  # Se till att detta refererar till din custom action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          parent_repository: tobbe-joh/noq_app_fork
          branch: main
          title: 'Update from FRONTEND submodule'
          body: 'This PR is to notify that the submodule has been updated.'
